# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.


- id: fuel-plugin-nfs-custom
  type: group
  role: [fuel-plugin-nfs-custom]
  requires: [deploy_start]
  required_for: [deploy_end]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig, hosts, firewall]
  parameters:
    strategy:
      type: one_by_one

- id: fuel-plugin-nfs-custom-install-nfs
  type: puppet
  groups: [fuel-plugin-nfs-custom]
  required_for: [deploy_end]
  requires: [netconfig]
  parameters:
    puppet_manifest: puppet/manifests/install.pp
    puppet_modules: puppet/modules/:/etc/puppet/modules
    timeout: 600

- id: fuel-plugin-nfs-custom-configure-cinder
  type: puppet
  groups: [cinder]
  required_for: [deploy_end]
  requires: [openstack-cinder]
  parameters:
    puppet_manifest: puppet/manifests/enable_nfs_backend.pp
    puppet_modules: puppet/modules/:/etc/puppet/modules
    timeout: 600

#- id: fuel-plugin-nfs-custom-post-deployment-sh
#  type: shell
#  role: [fuel-plugin-nfs-custom]
#  required_for: [post_deployment_end]
#  requires: [post_deployment_start]
#  parameters:
#    cmd: echo post_deployment_task_executed > /tmp/post_deployment
#    retries: 3
#    interval: 20
#    timeout: 180

#- id: fuel-plugin-nfs-custom-pre-deployment-sh
#  type: shell
#  role: [fuel-plugin-nfs-custom]
#  required_for: [pre_deployment_end]
#  requires: [pre_deployment_start]
#  parameters:
#    cmd: echo pre_deployment_task_executed > /tmp/pre_deployment
#    retries: 3
#    interval: 20
#    timeout: 180
